### ISSUE TITLE
(WBS 1.11.17) Errors related to project member roles

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#176]
There are two seemingly related errors related to project member roles:

1. When you are in a project and try to edit the team, you should be able to change a member's role by clicking on the role field, selecting the appropriate option from the drop-down menu, then pressing the Save button. However, at the moment, this isn't working; instead, when you press Save, you are taken to a blank white page that only contains the text "2024."
2. I believe we customized projets so that, for the DHSI 2023 group, you could choose what role new project members were given when they were added to a project synced with a parent group's membership. We may have also updated the site so that, by default, new project members added from parent groups were automatically added as Collaborators rather than Reviewers. However, it seems that setting the default role for new project members doesn't work.

Video clip of the first problem described above (which also shows that the default role for new project members is supposed to be "Collaborator," which isn't working): https://www.loom.com/share/af1983fcfcd048398c8f5f47541f622a?sid=b8890219-8e11-490b-9029-fdb1679c6f5b

**Comment by toanhminh0412** [comment]
Seems like this happens due to the language filter plugin being activated. If you turn if off, the feature works fine!

**Comment by toanhminh0412** [comment]
First point: I found out a way to deal with this problem. However, I will need to update this fix EVERY TIME WE ADD A NEW LANGUAGE. For documetation:
- Add language code to line 277 in `app/templates/mytemplate/html/plg_projects_team/team.js`

**Comment by ghjensen** [comment]
Wonderful! Thanks for this fix, Archie. I'll need to test it out a bit more, but I'll do that while you chip away at the second issue (above). And thanks for the important note re: documentation!

**Comment by toanhminh0412** [comment]
Second point: I made two extra changes:
* Made the default role to be "collaborator" when adding group members to a group project
* Developed a "Sync group members" button to sync all group members to a certain role of choice. Screenshot provided. (I'm not sure if this button will help at all. I can remove it if you don't like it)
![Screenshot 2024-02-13 225445](https://github.com/etcluvic/hsscommons/assets/55383509/f6e5a6b0-4fab-41ad-8c0a-b2d9e2ac5576)

**Comment by ghjensen** [comment]
Thanks, @toanhminh0412! This is looking great. The fix for the first issue is working properly for me, and "Collaborator" seems to be working as the default role within projects, too.

I have a few follow-up questions:

1. When I'm editing an **_existing_** project within a group, I don't see the drop-down that says "Sync members as..."; only the "Sync group members" button appears (see screenshot below). Do you know why the drop-down menu doesn't show up there? When I edit a project that I created after you implemented these changes, I _**do**_ see both the drop-down menu and the button, as I would expect, so I think we just need to make sure that these options are available for projects that already exist on the site, too.
2. The new "Sync group members" button seems to work well for the most part. Thanks for thinking of that! The only issue I noticed is that it doesn't seem to change the role for someone if I've already manually edited their role using the drop-down menu beside their name. For example, if I manually change John Doe from a collaborator to a reviewer and then try to use the "Sync group members" button to change everyone to a collaborator, it leaves John Doe as a reviewer. (It also leaves the manager[s] as managers, but that's a good thing, and we shouldn't change that.)

Oh, and one last thing re: #2: could you please change the button's label to "Sync group members to this role" (just to clarify what the button does a bit more)? Thanks!

<img width="1450" alt="Screenshot 2024-02-23 at 1 32 38 PM" src="https://github.com/etcluvic/hsscommons/assets/12787016/468b7bd7-e105-4ecd-a32c-6aada13eb5ea">

**Comment by toanhminh0412** [comment]
<img width="933" alt="Screenshot 2024-02-28 at 9 19 08 PM" src="https://github.com/etcluvic/hsscommons/assets/55383509/2391e92a-dafe-4315-bbdc-2813a7ca056a">

I changed the concept of the "Sync group members" a little. I now implemented a "Save" button which allows you switch between two modes:
- Include all group members
- Specify membership

If you are in the **Include all group members** mode, you will be able to see the drop down. Otherwise, you don't. If you select a role to sync all members to and click "Save", they will be synced.

This design makes more sense to me, let me know how you think

**Comment by toanhminh0412** [comment]
I don't have the second issue that you mentioned above. I can manually change a person's role and sync them, it still work. Please check if the person that you manually changed the role is a member of the group. Because you can only sync group members

**Comment by ghjensen** [comment]
Hey @toanhminh0412, I think I like this newest save button option you've created! Thanks. Let's go with this. There are just a few issues still remaining, though, from what I can see. Hopefully #2 and #3 are easy to address, though...

1. In a test project ("testproj") where I'm the manager: I selected "Include all group members", picked the "reviewer" role, and then clicked the save button, but then when I added Tim to the overarching group he was synced to the project as a collaborator, not as a reviewer. When I went back to the Edit Team page, the "Sync members as..." didn't have the reviewer option selected anymore, either (it had reverted to collaborator).
2. From a UX standpoint, I think we need to tweak the design slightly so that it's clear that the Save button applies to the first radio button option as well as the second one. Since it appears directly below the second radio button, I think people could easily get confused and not know that they need to press Save when changing options related to the first radio button. As a solution, could we duplicate create another Save button to go directly to the right of the "Sync members..." drop-down menu (so it's clear that you need to hit save when making a change there)?
3. Not a bug, but just a small request that might help address my comment re: the John Doe issue, above: could we change the wording for the "Sync members as..." drop-down menu to "Sync new members as..." (and adjust the width of the drop-down to fit the new text in, if necessary)? My understanding is that choosing a different role there only applies to people who are synced to the project _after_ a change is made, so I think this wording would make what's happening a bit more obvious.

**Comment by toanhminh0412** [comment]
So I've spent quite a bit of time trying to implement a more straightforward functionality for how the member options work as a whole.

Basically, you have 2 modes: **Specify memberships** and **Include all group members**. Here are the functionalities of each mode:

- You go to **specify memberships** if you want to delete members that belong to the owning group from the project. Plus, you can hide the **Sync member as** drop down.
- You go to **Include all group members** the first time to show the **Sync member as** drop down. Then you select something on that drop down, and hit save again to change the role of ALL group members in the project (except for the project creator and owner). Plus, when selecting something on the drop down and hitting save, it will also add all group members that are not in the project to the project.

Let me know what you think. Once we're good for the functionalities, I will start implementing the UI stuffs so that we don't waste time doing overlapping works.

**Comment by ghjensen** [comment]
Thanks, Archie. What you've outlined sounds good to me, and it fits with my understanding of how those parts of the site are supposed to work. But I think the first issue I outlined in my last message is still unresolved. It's this issue: "In a test project ("testproj") where I'm the manager: I selected "Include all group members", picked the "reviewer" role, and then clicked the save button, but then when I added Tim to the overarching group he was synced to the project as a collaborator, not as a reviewer. When I went back to the Edit Team page, the "Sync members as..." didn't have the reviewer option selected anymore, either (it had reverted to collaborator)." I just tested it again, and it's still adding new group members to a sub-project in the wrong role, and the wrong role is still not displaying when I navigate back to the "Edit Team" page. 

Let me know if it would be helpful to chat about this in person, or if you'd like a video of the issue instead.

Once we fix that, I think we'd be ready to proceed with implementing the UI changes listed above.

**Comment by toanhminh0412** [comment]
Right, I understand the issue and currently trying to implement a fix. This is more complicated that I thought.

**Comment by ghjensen** [comment]
No worries! Thanks for looking into this, Archie--we're really grateful for your help. :)

**Comment by toanhminh0412** [comment]
Ok I think I got it to work as expected. There are many components that get involved. Really hope it will work for you too this time! I also added some UI stuffs to explain the features a little. Let me know if you want any change to it!

**Comment by ghjensen** [comment]
Amazing! Thanks, Archie. I tested it out and all the bugs seem to have been addressed. I also really like how you simplified the drop-down menu to list only the project roles; that makes things look a lot cleaner.

I made a few small wording changes to the explanatory note and am now ready to close this issue. :)

**Comment by toanhminh0412** [comment]
I'm very glad to hear that it's working well for you guys! 

I recommend not closing the issue just yet though, as it's still not in production. I think we should wait until we see the feature is working in prod.

**Comment by ghjensen** [comment]
Thanks, Archie. From what I can tell, everything is now implemented and working on production except for one thing: if I'm a manager of a project but not the creator and I select Collaborators or Reviewers from the "Include all group members" drop-down, I get a 403 error right away (see screenshot) and can no longer access the "Edit Team" page. I think this happens because it doesn't protect my status as a manager, as I expected; it demotes me to a collaborator or reviewer, too.

Would it be possible to make creators _and_ managers exempt from role changes? Otherwise the 403 error will be pretty common, I think...
![Screenshot 2024-03-13 at 1 27 16 PM](https://github.com/etcluvic/hsscommons/assets/12787016/a5137f85-434a-4e0a-b261-3751536781eb)

**Comment by toanhminh0412** [comment]
Alright, I fixed the issue. Now managers will be exempted from the role changes. You can test it on the Test server

**Comment by ghjensen** [comment]
Awesome! Thanks, Archie. It's working for me now, too. :)

**Comment by ghjensen** [comment]
Everything looks good on prod, too, so I'm closing this issue. Thanks again!
