### ISSUE TITLE
WBS 1.1.6: Fix visibility of "delete" buttons

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#18]
When adding/editing publications, if you click the delete icon beside files on the "Content" tab/page or an author on the "Authors" tab/page, the confirmation buttons open up in a part of the field that isn't visible unless you scroll down and to the left (see screenshot from authors page). Screenshot: [https://drive.google.com/file/d/1T8gyyl2TkP_UE5AgQlGorLECM-soQtwI/view](https://drive.google.com/file/d/1T8gyyl2TkP_UE5AgQlGorLECM-soQtwI/view).

**Comment by toanhminh0412** [comment]
Fixed in pull request #22

**Comment by ghjensen** [comment]
This still appears to be an issue on the test instance: https://www.loom.com/share/315842f28d614dda9443b561e02e7371.
